# Generated by Django 3.2.9 on 2021-12-06 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0003_alter_box_user_pk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='pair',
            field=models.CharField(max_length=10),
        ),
    ]
