# Generated by Django 3.2.9 on 2021-12-09 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0009_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='money',
            name='board_number',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='pool.board'),
        ),
    ]
