# Generated by Django 3.2.9 on 2021-12-09 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0010_money_board_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='board_number',
            field=models.IntegerField(default=''),
        ),
    ]
