# Generated by Django 3.2.9 on 2021-12-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0012_board_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='email',
            field=models.CharField(default='', max_length=42),
        ),
    ]
