# Generated by Django 3.2.9 on 2021-12-10 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0013_box_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='box',
            old_name='email',
            new_name='username',
        ),
    ]
