# Generated by Django 3.2.9 on 2021-12-10 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0014_rename_email_box_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='box',
            name='user_pk',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='pool.user'),
        ),
    ]
