# Generated by Django 3.2.9 on 2021-12-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0016_auto_20211212_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='balance',
            field=models.FloatField(default=0),
        ),
    ]
