# Generated by Django 3.2.9 on 2021-12-13 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pool', '0017_box_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Winnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(default=0)),
                ('username', models.CharField(default='', max_length=42)),
                ('board_pk', models.CharField(default='', max_length=42)),
                ('user_pk', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
