# Generated by Django 3.2.9 on 2021-12-17 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0018_winnings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='money',
            old_name='first',
            new_name='four',
        ),
        migrations.RenameField(
            model_name='money',
            old_name='fourth',
            new_name='one',
        ),
        migrations.RenameField(
            model_name='money',
            old_name='second',
            new_name='three',
        ),
        migrations.RenameField(
            model_name='money',
            old_name='third',
            new_name='two',
        ),
    ]
