# Generated by Django 3.2.9 on 2021-12-22 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0019_auto_20211217_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='hit',
            field=models.BooleanField(default=False),
        ),
    ]
