# Generated by Django 3.2.9 on 2021-12-23 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0021_box_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarchMadness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final', models.FloatField()),
                ('board_number', models.IntegerField(default='')),
            ],
        ),
    ]
