# Generated by Django 3.2.9 on 2021-12-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0022_marchmadness'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marchmadness',
            name='final',
        ),
        migrations.AddField(
            model_name='marchmadness',
            name='championship',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='marchmadness',
            name='elite_eight',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='marchmadness',
            name='final_four',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='marchmadness',
            name='first_round',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='marchmadness',
            name='second_round',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='marchmadness',
            name='sweet_sixteen',
            field=models.FloatField(default=0),
        ),
    ]
