# Generated by Django 3.2.9 on 2021-12-27 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0023_auto_20211227_1124'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Money',
            new_name='NFL',
        ),
    ]
