# Generated by Django 3.2.9 on 2021-12-27 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0025_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='board_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pool.board'),
        ),
    ]
