# Generated by Django 3.2.9 on 2021-12-28 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0026_alter_admin_board_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='type',
            field=models.CharField(default='', max_length=10),
        ),
    ]
