# Generated by Django 3.2.9 on 2022-01-14 17:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0028_board_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winning', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), default=list, size=None)),
                ('losing', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), default=list, size=None)),
                ('board_pk', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
