# Generated by Django 3.2.9 on 2022-01-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0029_generatednumbers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team', models.CharField(max_length=20)),
                ('away_team', models.CharField(max_length=20)),
                ('home_team_score', models.IntegerField(default='')),
                ('away_team_score', models.IntegerField(default='')),
            ],
        ),
    ]
