# Generated by Django 3.2.9 on 2022-01-14 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0030_scrapedata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapedata',
            name='away_team_score',
        ),
        migrations.RemoveField(
            model_name='scrapedata',
            name='home_team_score',
        ),
    ]
