# Generated by Django 3.2.9 on 2022-01-24 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0031_auto_20220114_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='name',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
