# Generated by Django 3.2.9 on 2022-01-24 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0033_auto_20220124_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marchmadness',
            name='board_number',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='nfl',
            name='board_number',
            field=models.IntegerField(default=''),
        ),
    ]
