# Generated by Django 3.2.9 on 2022-01-28 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0037_box_box_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='box_price',
        ),
        migrations.AddField(
            model_name='board',
            name='box_price',
            field=models.FloatField(default=0),
        ),
    ]
