# Generated by Django 3.2.9 on 2022-02-01 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0038_auto_20220128_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='first_name',
            field=models.CharField(default='', max_length=42),
        ),
    ]
