# Generated by Django 3.2.9 on 2022-02-01 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0039_box_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='winnings',
            name='first_name',
            field=models.CharField(default='', max_length=42),
        ),
    ]
