# Generated by Django 3.2.9 on 2022-03-07 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0040_winnings_first_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarchMadnessDates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
            ],
        ),
    ]
